services:
  - type: web
    name: validation-script
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn beta2:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 